### ISSUE TITLE
bigintmin/bigintmax tests fail

### ISSUE THREAD

**Issue by GeoffMontee** [tds-fdw/tds_fdw#66]
The bigintmin/bigintmax tests are failing on the CI.

```
[ERROR] Error running test tests/postgresql/009_bigintmin.sql
[ERROR] 22003
[ERROR] ERROR:  value "-9223372036854775808" is out of range for type integer

[INFO] Running tests/postgresql/010_bigintmax.sql
[ERROR] Error running test tests/postgresql/010_bigintmax.sql
[ERROR] 22003
[ERROR] ERROR:  value "9223372036854775807" is out of range for type integer
```

**Comment by GeoffMontee** [comment]
@juliogonzalez,

Do you know why these tests are failing? I can select from these tables directly without any problems:

```
postgres=# select * from bigint_max;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
 id |        value
----+---------------------
  1 | 9223372036854775807
(1 row)

postgres=# select * from bigint_min;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
 id |        value
----+----------------------
  1 | -9223372036854775808
(1 row)
```

**Comment by GeoffMontee** [comment]
Ah, it seems to be the queries like this:

```
postgres=# SELECT (value = -9223372036854775808) AS pass FROM bigint_min;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
ERROR:  value "-9223372036854775808" is out of range for type integer
```

**Comment by GeoffMontee** [comment]
These also fail for some reason:

```
postgres=# SELECT (value = '-9223372036854775808'::bigint) AS pass FROM bigint_min;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
ERROR:  value "-9223372036854775808" is out of range for type integer
postgres=# SELECT (value::bigint = '-9223372036854775808'::bigint) AS pass FROM bigint_min;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
ERROR:  value "-9223372036854775808" is out of range for type integer
```

**Comment by GeoffMontee** [comment]
It definitely seems to be something that tds_fdw is doing because the query works fine for a local table:

```
postgres=# CREATE TABLE local_bigint_min (
postgres(#         id int primary key,
postgres(#         value bigint
postgres(# );
CREATE TABLE
postgres=#
postgres=# INSERT INTO local_bigint_min (id, value) VALUES (1, -9223372036854775808);
INSERT 0 1
postgres=#
postgres=# SELECT (value = -9223372036854775808) AS pass FROM local_bigint_min;
 pass
------
 t
(1 row)

postgres=# SELECT (value = -9223372036854775808) AS pass FROM bigint_min;
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5701, Msg state: 2, Msg: Changed database context to 'tds_fdw_jenkins'., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
NOTICE:  DB-Library notice: Msg #: 5703, Msg state: 1, Msg: Changed language setting to us_english., Server: mgaf1hvpnc, Process: , Line: 1, Level: 0
ERROR:  value "-9223372036854775808" is out of range for type integer
```

**Comment by GeoffMontee** [comment]
It looks like tds_fdw is not using the raw conversions for this field. Instead, it's converting the value to a string, and then it looks like PostgreSQL converts the string to an integer (instead of a bigint).

It should be doing a raw conversion when it follows this codepath: https://github.com/tds-fdw/tds_fdw/blob/da3c823fdbbe697331cd213bd1cd40f8864c72c4/src/tds_fdw.c#L1613

I can see that the data type from the foreign source is SYBINT8, so maybe the problem is that the local field's OID isn't INT8OID for some reason.

**Comment by GeoffMontee** [comment]
It looks like column->attr_oid is always 0 when match_column_names is not set, because I forgot to set it in this block: https://github.com/tds-fdw/tds_fdw/blob/da3c823fdbbe697331cd213bd1cd40f8864c72c4/src/tds_fdw.c#L1448

**Comment by juliogonzalez** [comment]
Mmmm... I can see any PostgreSQL version change since it stopped working:

Working at: https://jenkins.juliogonzalez.es/job/tds_fdw-build/146/PG_VER=9.5,label=centos6/console
Not working at: https://jenkins.juliogonzalez.es/job/tds_fdw-build/PG_VER=9.5,label=centos6/167/console

And both are 9.5rc1 (CentOS, and by the way I need to update this).

However it's the same for Ubuntu:
Working: https://jenkins.juliogonzalez.es/job/tds_fdw-build/146/PG_VER=9.5,label=ubuntu12.04/console
Not working: https://jenkins.juliogonzalez.es/job/tds_fdw-build/PG_VER=9.5,label=ubuntu12.04/167/console

And both 9.5.1-1.pgdg12.4+1

Could it be something that changed at Azure?

**Comment by GeoffMontee** [comment]
The last commit should fix the problem with column->attr_oid, so we will see if that fixes the test: https://github.com/tds-fdw/tds_fdw/commit/58921433b37f4b2aa909ea462119e27e9993cb73

The commit changelog is really messed up because I think I committed it with the wrong newline characters.

@juliogonzalez,

It looks like Jenkins is still trying to clone the repository from the old URL. Is that something you need to fix on your end?

**Comment by juliogonzalez** [comment]
@GeoffMontee, the old URL still works as an alias so nobody need to do changes on their side (people working as contributors with the old GIT remote).

You can see at https://jenkins.juliogonzalez.es/job/tds_fdw-build/PG_VER=9.5,label=centos6/168/console that 5892143 is being tested:
```
17:01:39  > git fetch --tags --progress https://github.com/GeoffMontee/tds_fdw.git +refs/heads/*:refs/remotes/origin/*
17:01:54 Checking out Revision 58921433b37f4b2aa909ea462119e27e9993cb73 (refs/remotes/origin/master)
17:01:59  > git config core.sparsecheckout # timeout=10
17:01:59  > git checkout -f 58921433b37f4b2aa909ea462119e27e9993cb73
```
However it's always better to use the current URL so the origin is 100% clear at the logs.

I'll reconfigure the CI right now :-)

**Comment by juliogonzalez** [comment]
It seems the problem is still present at after the patch CentOS/Ubuntu and >= 9.2: https://jenkins.juliogonzalez.es/job/tds_fdw-build/169/

**Comment by GeoffMontee** [comment]
This problem was still present because tds_fdw was using the attr_oid for the wrong column in this particular query when match_column_names was off.

I basically had to disable the new column pushdown feature when match_column_names is off. When match_column_names is off, all columns needs to be fetched, since the position of the remote column is used to match it with its corresponding local column, rather than its name.

This commit changelog also seems to be messed up: https://github.com/tds-fdw/tds_fdw/commit/0fd8752dad80dc8790dacaa9c5a250fed55a4f99

**Comment by GeoffMontee** [comment]
I went ahead and turned on match_column_names by default. Since the next release will be a new major release, I think a change in defaults is OK.

After I did that, I discovered that the column pushdown feature had broken match_column_names too, so I also fixed that.

I also added a .gitattributes file with a line ending configuration set, so hopefully that will help keep line endings consistent.

**Comment by juliogonzalez** [comment]
Seems to be working great for >=9.2

Do we need to add more tests? What shall we do about 9.1?

**Comment by GeoffMontee** [comment]
> Do we need to add more tests?

Based on the failures that I saw today, we probably need tests covering the following cases:

* A test that sets match_column_names to 1 and then selects a subset of a foreign table's columns, not starting at the first one. e.g.:

```
CREATE FOREIGN TABLE match_column_names1 (
        id int,
        value bigint
)
        SERVER mssql_svr
        OPTIONS (table 'dbo.bigint_min', row_estimate_method 'showplan_all', match_column_names 1);

SELECT value FROM match_column_names1;
```

* A test that sets match_column_names to 0 and then selects a subset of a foreign table's columns, not starting at the first one. e.g.:

CREATE FOREIGN TABLE match_column_names0 (
        id int,
        value bigint
)
        SERVER mssql_svr
        OPTIONS (table 'dbo.bigint_min', row_estimate_method 'showplan_all', match_column_names 0);

SELECT value FROM match_column_names0;
```

Should we have these new tests select from dbo.bigint_min in Azure, or should we create new tables just for these tests?

> What shall we do about 9.1?

I'm going to think about that some more, but I'm guessing that we will have to remove support for it.

**Comment by juliogonzalez** [comment]
In theory we could reuse dbo.bigint_min, but I think we'll create a new table for the match column names tests, so it's not confusing if something fails and we get an error.

I'll prepare a PR for it in a few minutes.

**Comment by juliogonzalez** [comment]
Tests are implemented at one of my branches, but I'm testing and getting:

19:25:40 [INFO] Running tests/postgresql/027_column_match_enabled.sql
19:25:40 [ERROR] Error running test tests/postgresql/027_column_match_enabled.sql
19:25:40 [ERROR] 42601
19:25:40 [ERROR] ERROR:  Redundant option: match_column_names (1)
19:25:40 
19:25:40 [INFO] Running tests/postgresql/028_column_match_disabled.sql
19:25:40 [ERROR] Error running test tests/postgresql/028_column_match_disabled.sql
19:25:40 [ERROR] 42601
19:25:40 [ERROR] ERROR:  Redundant option: match_column_names (0)
19:25:40 

(for example https://jenkins.juliogonzalez.es/job/tds_fdw-build-ng/PG_VER=9.5,label=centos6/4/console)

Code for both tests at: https://github.com/juliogonzalez/tds_fdw/tree/match_column_tests/tests/tests/postgresql

Any hint?

NOTE: match_column_names is not present at SERVER creation (https://github.com/juliogonzalez/tds_fdw/blob/match_column_tests/tests/tests/postgresql/001_create_server.sql)

**Comment by GeoffMontee** [comment]
It looks like your new tests are finding bugs already!

I just fixed that.

**Comment by juliogonzalez** [comment]
Sounds good!

Let me rebase your changes into my branch and test my PR again :-)
